//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGateIn.UI.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartGateIn.UI.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;---- Please press to return to the prior screen.
        /// </summary>
        internal static string Common_Backwards {
            get {
                return ResourceManager.GetString("Common_Backwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Common_Confirm {
            get {
                return ResourceManager.GetString("Common_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Note Number.
        /// </summary>
        internal static string Common_DeliveryNoteNumber {
            get {
                return ResourceManager.GetString("Common_DeliveryNoteNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Content Code.
        /// </summary>
        internal static string Common_DisplayNameForContentCodeDescriptionInTables {
            get {
                return ResourceManager.GetString("Common_DisplayNameForContentCodeDescriptionInTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name.
        /// </summary>
        internal static string Common_DisplayNameForSupplierNameInTables {
            get {
                return ResourceManager.GetString("Common_DisplayNameForSupplierNameInTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll down.
        /// </summary>
        internal static string Common_ScrollDown {
            get {
                return ResourceManager.GetString("Common_ScrollDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll up.
        /// </summary>
        internal static string Common_ScrollUp {
            get {
                return ResourceManager.GetString("Common_ScrollUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start over.
        /// </summary>
        internal static string Common_StartOver {
            get {
                return ResourceManager.GetString("Common_StartOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Number.
        /// </summary>
        internal static string Common_SupplierNumber {
            get {
                return ResourceManager.GetString("Common_SupplierNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout. Please start the check-in again..
        /// </summary>
        internal static string Common_TimeoutMessage {
            get {
                return ResourceManager.GetString("Common_TimeoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailer Number.
        /// </summary>
        internal static string Common_TrailerNumber {
            get {
                return ResourceManager.GetString("Common_TrailerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip ID.
        /// </summary>
        internal static string Common_TripId {
            get {
                return ResourceManager.GetString("Common_TripId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose Hall for returnable.
        /// </summary>
        internal static string FormAvailableSuperGroups_Instruction {
            get {
                return ResourceManager.GetString("FormAvailableSuperGroups_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose  below to confirm for a {0}, {1} or {2}..
        /// </summary>
        internal static string FormAvailableTrailers_Instruction {
            get {
                return ResourceManager.GetString("FormAvailableTrailers_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} found, please choose {1} or {2}..
        /// </summary>
        internal static string FormAvailableTrailers_NoResultsFound {
            get {
                return ResourceManager.GetString("FormAvailableTrailers_NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to continue.
        /// </summary>
        internal static string FormInitialScreen_Continue {
            get {
                return ResourceManager.GetString("FormInitialScreen_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string FormInitialScreen_Instruction {
            get {
                return ResourceManager.GetString("FormInitialScreen_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan the Trip ID from your summary sheet..
        /// </summary>
        internal static string FormPackingSlip_AskUserToInsertTripSummarySheet {
            get {
                return ResourceManager.GetString("FormPackingSlip_AskUserToInsertTripSummarySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan the following from your BOL / packing slip.
        /// </summary>
        internal static string FormPackingSlip_Instruction {
            get {
                return ResourceManager.GetString("FormPackingSlip_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ASN was found matching the criterias..
        /// </summary>
        internal static string FormPackingSlip_NoAsnFound {
            get {
                return ResourceManager.GetString("FormPackingSlip_NoAsnFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose part family from below.
        /// </summary>
        internal static string FormPartFamilies_Instruction {
            get {
                return ResourceManager.GetString("FormPartFamilies_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to confirm tickets printed successfully.
        /// </summary>
        internal static string FormSendConfirmation_PrintedSuccessfully {
            get {
                return ResourceManager.GetString("FormSendConfirmation_PrintedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets have not been printed successfully.
        /// </summary>
        internal static string FormSendConfirmation_PrintingFailed {
            get {
                return ResourceManager.GetString("FormSendConfirmation_PrintingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you receive the ticket?.
        /// </summary>
        internal static string FromSendConfirmation_Instruction {
            get {
                return ResourceManager.GetString("FromSendConfirmation_Instruction", resourceCulture);
            }
        }
    }
}
